### ISSUE TITLE
Is it impossible to have parameters for HE with Level<32? 

### ISSUE THREAD

**Issue by wanghs09** [tlepoint/homomorphic-simon#2]
Hi all,

I'm trying to design parameters to homomorphicly evaluate a function with a multiplication level=5, but according to the publication[1], in order to avoid ciphertext expansion, it was proposed to use block cipher+FHE scheme[NLV11]. 

Since a block cipher such as SIMON-32 has a minimum multiplication level 32, the FHE level has to be 32, even for my function it only needs to be 5. Is that so?

Thanks in advance if you kindly answer it.

Kind regards,
Husen

[1] A comparison of the Homomorphic Encryption Schemes FV and YASHE

**Comment by tlepoint** [comment]
Hi,

Your parameters should be for level 32+5 = 37. If you don't care about the ciphertext expansion, which will be kinda small, you can select parameters for level 5 and not use SIMON-32.

Regards,

**Comment by wanghs09** [comment]
Thanks a lot for the explanation, Tancrède :)
But I do have a question about your another paper "Stream ciphers: A Practical Solution for Efficient Homomorphic-Ciphertext Compression". 
Suppose the circuit I want to evaluate is depth L1 and the stream cipher depth is L2. 
For FHE, as long as L2<L1, there will be no need for bootstrapping during ciphertext decompression. Actually for FHE, any L2 will not be a problem with bootstrapping.
For somewhat HE, a smaller L2 will allow the total depth L1+L2 smaller.
So  the solution is more meaningful to somewhat HE, right?

Besides, stream ciphers only allows bit operations, but sometimes somewhat HE needs plaintext space t>2, such as t=2^10 for low depth circuit, how can we deal with this contradiction? 

Best regards,
Husen

**Comment by tlepoint** [comment]
The solution is also interesting for FHE because it reduces the number of bootstrappings (the current bottleneck in FHE implementations).

For the plaintext space, this is a good question. Our paper was indeed focusing on bits or bit-vectors. If you work with something larger, you either need to come up with a different stream cipher, or you need to compute the arithmetic circuit corresponding to XORs and ANDs : 
- AND is a multiplication
- a XOR b = a+b-2ab
  and you can do this regardless of the plaintext space. The downside is that it also requires a multiplication by XOR gate.

Best.

**Comment by wanghs09** [comment]
Thanks Tancrède!
Indeed the bootstrapping numbers can be reduced since the equivalent circuit depth is smaller.

I figured out later that if the plaintext space t>2, the binary decomposition of one integer can be encoded into different SIMON-32/64 ciphertexts so that they can be homomorphically decrypted into different slots of one/several ciphertexts, the to recover the original integer, one level multiplication+ log level addition are needed, such as 6={1,0,1}*{2^2, 2^1, 2^0}.  But to have a large plaintext space and depth at the same time is problematic.

"Towards Stream Ciphers for Efficient FHE with Low-Noise Ciphertexts" this year might give a solution for small depth stream ciphers. :)

Best regards!
Husen
