### ISSUE TITLE
Is YASHE thread-safe?

### ISSUE THREAD

**Issue by hilder-vitor** [tlepoint/homomorphic-simon#3]
Hello.

I just want to know if this implementation of the YASHE scheme is thread-safe.  Because I am planing to use it on a multi-thread application...

Thank you very much!

**Comment by tlepoint** [comment]
Hi

Yes, OpenMP was used at several places in Simon.cpp for example.

Regards,

**Comment by hilder-vitor** [comment]
Ok. Thank you!
